### ISSUE TITLE
Implementierung des Medizin-Pfades

### ISSUE THREAD

**Issue by noopliez** [Schlaue-Lise-IT-Project/schlaue-lise#11]
Der Medizin-Pfad muss lauffähig gemacht werden. Aktuell fehlt auf dem `main` Branch noch eine solche stabile Version. 

Anforderungen:

- [x] Anwender:innen bekommen auf Nachfrage entsprechend Hilfe für medizinische Aspekte

**Comment by Pusteblum3** [comment]
direktpfad funktioniert nun. 
- "normales durchlaufen" mit ja und nein antwort funktioniert 
- info eingabe mit versicherungsstatus und notfallstatus klappt > darauf folgt Abfrage des fehlenden Slots 
- info über beides (versicherungs- und notfallstatus) werden aus text übernommen und entsprechend in slots gespeichert
