### ISSUE TITLE
README aus URL übernehmen

### ISSUE THREAD

**Issue by Lena-Holderrieth** [Schlaue-Lise-IT-Project/schlaue-lise#18]
in der README auf Branch lena/url steht noch, wie man die Variable konfigurieren muss, falls da Probleme auftreten

=> das hast du vergessen zu übernehmen

- [x] README um den Hinweis zur Timeout-Variable erweitern

**Comment by noopliez** [comment]
Hi Lena, mit `- [ ]` kannst du mir Tasks erstellen, die erst abgearbeitet werden müssen, damit die Issue geschlossen werden kann. 

Ich erstell mir mal selbst einen: 

- [ ] README um den Hinweis zur Timeout-Variable erweitern
