### ISSUE TITLE
Vortrag: Folien anschauen

### ISSUE THREAD

**Issue by Lena-Holderrieth** [Schlaue-Lise-IT-Project/schlaue-lise#19]
- [x] Meine neuen Folien anschauen

**Comment by noopliez** [comment]
Grundsätzlich erstmal mega geil umgesetzt. Das einzige was mich verwirrt, ist die Tatsache, dass du nie den Inhalt der Files zeigst. Das wäre vll ein Punkt, über den wir nochmal quatschen sollten. Oder du sagst, dass du da keinen Bock drauf hast 😄

**Comment by noopliez** [comment]
Ist ja geklärt, kannst ja reopen, wenn du wieder willst, dass ich drüberschau
