### ISSUE TITLE
Bug: Spendeartikel werden nicht erkannt

### ISSUE THREAD

**Issue by Lena-Holderrieth** [Schlaue-Lise-IT-Project/schlaue-lise#20]
Der Bot erkennt die Spendenartikel (setzt auch die Slots richtig), reagiert aber trotzdem mit utter_default.

Reproduktion:
`ich brauch was`
`ich brauch einen Pullover, eine Decke, ein Handy`

Dadurch kommt man in der Konversation nicht weiter.

**Comment by MarieConstantin** [comment]
![grafik](https://user-images.githubusercontent.com/77720016/143060306-01a76d4f-a559-4766-8c02-4aadb77e3861.png)

aktuell stoppt das Programm bei mir schon im ersten Schritt mit einer Fehlermeldung, ein utter_default wird bis dahin noch nirgendwo erkannt. Fehler konnte ich somit bisher noch nicht reproduzieren :/

**Comment by MarieConstantin** [comment]
@Lena-Holderrieth 

![grafik](https://user-images.githubusercontent.com/77720016/143230109-083244a1-c0ee-48b2-9294-3e1833fbdcc4.png)

Fehler konnte soweit reproduziert werden, sofern alles so erkannt wurde wie gewünscht, da bitte Rückmeldung geben, das weiß ich nicht natürlich nicht genau. 
Frage: Was genau soll statt dem default_fallback denn erkannt werden?
