### ISSUE TITLE
Feature: Direkter Sprung zu Schlafen Endpoints

### ISSUE THREAD

**Issue by noopliez** [Schlaue-Lise-IT-Project/schlaue-lise#21]
Momentan kommt man noch nicht per direkter Eingabe (Bsp. siehe unten) zu einem der Endpoints (Views) von `Schlafen`. Man muss zwingend durch die Informationen-Form. 

Die Frage ist auch, ob das überhaupt notwendig ist, da man es ja durchaus als Nutzer:in versuchen kann, aber nicht so weit kommt. 

Folgendes funktioniert nicht: 

```sh
Input: Ich bin 32 Jahre alt, männlich, habe keinen Hund, bin nicht drogenabhängig und suche eine Notunterkunft.
```

Nach dieser Eingabe erkennt der Bot folgende Entities:

```python
{
  "alter": "32",
  "geschlecht": "männlich"
}
```

Ordnet sie dem Intent `inform` zu und ruft die `informationen_form` auf. Dort wird er dann nach den fehlenden Informationen befragt. Der Bot schafft es zumindest bei mir, dass er dann auch nach der Unterkunft fragt. Das kann sich aber ändern, wenn mehr auf dem main gemerged wurde.

Mal abgesehen davon, dass ich es für unrealistisch halte, dass jemand sich den Aufwand gibt, das alles einzutragen, bin ich der Meinung, dass es ein viel zu großer Aufwand für uns wäre, das zu implementieren. 

Das scheitert schon an der Frage: "Wie unterscheide ich zwischen einer **langfristigen** und einer **Not**-Unterkunft?"

Oder: "Wie erkenne ich, dass ein Mensch **NICHT** drogenabhängig ist?"

Dieser Issue ist erstmal nur zur Diskussion gedacht.

**Comment by noopliez** [comment]
Ich habe das gestern nochmal getestet und es funktioniert immer noch (habe eine zusätzliche Rule implementiert). Ich sehe weiterhin keinen Bedarf darin, diesen Shortcut umzusetzen. Meine Argumente bleiben dieselben wie oben 🙂 :

> [...] für unrealistisch halte, dass jemand sich den Aufwand gibt, das alles einzutragen, bin ich der Meinung, dass es ein viel zu großer Aufwand für uns wäre, das zu implementieren.

**Comment by MarieConstantin** [comment]
Ich sehe dass zwar auch so, dass das ein enormer Aufwand sein würde dass zu implementieren, den sich grad keiner mehr leisten kann, allerdings gehören die Shortcuts/Deep Links mit zu den Main-Features die der Herr Riedhammer immer haben wollte. Ich weiß nicht ob dass so gut ist, das weg zulassen. Bin da zwiegespaltener Meinung.

**Comment by noopliez** [comment]
> [...] gehören die Shortcuts/Deep Links mit zu den Main-Features die der Herr Riedhammer immer haben wollte.

"Klappt" ja auch, bloß springt der Bot dann noch zusätzlich in eine Form, weil er nicht zwischen "ich nehme Drogen" und "ich nehme keine Drogen" unterscheiden kann. Und das checkt er in der Form ab. Also der/die Nutzer:in kann es gern versuchen, aber es wird nicht erfolgreich sein, sondern vom Bot entsprechend abgefangen.

**Comment by Lena-Holderrieth** [comment]
Max probierts heute zu fixen, Marie koordiniert den Rest.
