### ISSUE TITLE
Discussion: Prüfen von Entities in nlu_main.yml

### ISSUE THREAD

**Issue by noopliez** [Schlaue-Lise-IT-Project/schlaue-lise#22]
Bisher werden die Entities `haustier` und `drogen` befüllt, sobald entsprechende Wörter erkannt werden. Bisher haben sie aber noch keinen Zweck. Möglicherweise kann man sie dazu benutzen, um einen direkten Pfad (siehe #21 ) zu generieren (allerdings ist die Negation schwierig).

**Comment by noopliez** [comment]
Meine Meinung dazu: 

Sie sind jetzt da, tun niemandem weh und können bleiben.

**Comment by Lena-Holderrieth** [comment]
einstimmig beschlossen.
