### ISSUE TITLE
responses_main.yml aufteilen

### ISSUE THREAD

**Issue by MarieConstantin** [Schlaue-Lise-IT-Project/schlaue-lise#28]
Die responses_main.yml ist unübersichtlich mit den Altern, Geschlecht etc. Dingen.
In der Main sollten nur die allgemeinen Hallo, Tschüsse, Ja, Nein Sachen stehen, nichts spezifisches schon zu unserer Thematik.
Bitte die anderen Sachen dementsprechend in andere Files auslagern

**Comment by noopliez** [comment]
Hier ist kein PR verlinkt und ich finde auch keinen. Warum ist das auf **Review in progress**?

**Comment by noopliez** [comment]
Sehe gerade, dass das schon auf der `main` ist. Ich schließe damit den Issue.
