### ISSUE TITLE
Bug: Bot fragt immer weiter nach Alter

### ISSUE THREAD

**Issue by MarieConstantin** [Schlaue-Lise-IT-Project/schlaue-lise#30]
![grafik](https://user-images.githubusercontent.com/77720016/143063938-7495f8d1-c511-4d3e-84a3-9905a8341976.png)

Ignoriert die Fehlerhaften Antworten die der Bot hier am Anfang gibt. Meine Frage, bzw. den Bug den ich hier melde ist die Tatsache, dass immer weiter nach dem Alter gefragt wird obwohl wir in einem anderen Gespräch drinnen sind. Es sollte hier meiner Meinung nach nicht weiter nach dem Alter gefragt werden.
Wisst ihr woran das liegt?
bzw. könnt ihr es vllt. direkt lösen?

**Comment by noopliez** [comment]
![Screen Shot 2021-11-25 at 18 45 07](https://user-images.githubusercontent.com/71688793/143484491-381adc2d-88fb-4cc5-a867-dc5925f8c7c8.png)

Habe das mit der aktuellsten Version auf Rasa X Server nicht mehr...
