### ISSUE TITLE
Nachschauen: mehrere Spendenartikel (inklusive Hygieneartikel) => was passiert dann?

### ISSUE THREAD

**Issue by Lena-Holderrieth** [Schlaue-Lise-IT-Project/schlaue-lise#41]

**Comment by Lena-Holderrieth** [comment]
![grafik](https://user-images.githubusercontent.com/94544385/143461897-c283f921-3c39-4b9d-8905-57f509607c6f.png)
Wie man hier sieht, wird alles richtig erkannt (erkennbar an URL), die Seife wird aber bei Spenden nicht aufgeführt.
Soll diese Kombi noch möglich sein?

**Comment by noopliez** [comment]
Das is ne gute Frage, ob das überhaupt geht. Wenn man `Seife` sowohl als `hygieneartikel` als auch als `spendenartikel` annotiert, kann ich mir vorstellen, dass das zu Problemen führt. Eine Überlegung wäre, dass man in der Form noch angibt, dass Entities auch aus `hygieneartikel` extrahiert werden.

**Comment by Lena-Holderrieth** [comment]
Also ich habs für Spenden angepasst. Ich hab auch ne Idee, wie ichs für Hygiene noch anpassen kann. Muss ich aber erst ausprobieren.
