### ISSUE TITLE
URL an jede Story hängen

### ISSUE THREAD

**Issue by Lena-Holderrieth** [Schlaue-Lise-IT-Project/schlaue-lise#44]
An jede Story 
`action: action_answer_url`
anhängen

- [x] Schlafen
- [x] Spenden
- [x] Medizin
- [x] Hygiene

Bitte auch an die Rules hinzufügen!

**Comment by Lena-Holderrieth** [comment]
Spenden hab ich schon gemacht.
Den Rest kannst du einfach easy in VSC machen, brauchst kein Rasa dafür.

**Comment by Sebastian-Klement** [comment]
Action_answer_url in stories Schlafen und Spenden eingefügt.

**Comment by Pusteblum3** [comment]
die action für die urls ist für medicine an jede story und rule nun eingefügt

**Comment by noopliez** [comment]
Ich schließ das mal
