### ISSUE TITLE
Bot reagiert nicht auf Danke am Ende

### ISSUE THREAD

**Issue by noopliez** [Schlaue-Lise-IT-Project/schlaue-lise#45]
Bot reagiert nicht auf ein 'Danke' am Ende einer Story. Er vermutet ein `greet` und startet daraufhin eine neue Story (in meinem Fall hat er auf einmal die `informationen_form` aufgerufen. 

![Screen Shot 2021-11-25 at 16 25 25](https://user-images.githubusercontent.com/71688793/143468214-1b5ce507-75a1-41d1-bdf0-3ac53fef182b.png)

- [x] Intent für eine Verabschiedung erstellen

**Comment by Sebastian-Klement** [comment]
MR erstellt.

**Comment by Sebastian-Klement** [comment]
Würde hier nicht eine rule reichen? Ich habe mal eine geschrieben, intents und action auch.
