### ISSUE TITLE
Bug: Trainingsdaten von Medizin sind möglicherweise fehlerhaft

### ISSUE THREAD

**Issue by noopliez** [Schlaue-Lise-IT-Project/schlaue-lise#51]
Wenn ich `rasa train` auf `main` starte, werden folgende Warnungen produziert: 

![Screen Shot 2021-11-26 at 10 17 01](https://user-images.githubusercontent.com/71688793/143559746-582c140f-88ef-466b-92a5-4e8d03549ba8.png)

![Screen Shot 2021-11-26 at 10 17 14](https://user-images.githubusercontent.com/71688793/143559762-6cfb50b9-a3b2-4d65-9e11-d823af3f4db7.png)

Außerdem versucht Rasa X (was diese Unstimmigkeiten erkennt), das folgendermaßen auszubessern:

![Screen Shot 2021-11-26 at 10 18 49](https://user-images.githubusercontent.com/71688793/143559833-86ddacb8-5fe7-407d-a3b1-5840e9d5cbda.png)

Ich vermute, es liegt daran, weil du versucht Bool-Werte in den Intents per Entity zu setzen, statt über die Forms.

**Comment by Pusteblum3** [comment]
![image](https://user-images.githubusercontent.com/56924575/143776366-9b62cd11-069b-4731-b52b-d76c142ef64e.png)
habe jetzt die Synonyme in die intents verlagert (siehe screenshot). 
Die angemerkten Warnungen tauchen so nicht mehr auf. Pushe den Stand jetzt gleich auf meinen branch tanja/medicine. 
ist jetzt sicher nicht die eleganteste Lösung, aber die Warnungen sind somit weg. 
Kann die issue somit auf done gesetzt werden und die Sache dann in die nächste Mergerequest für den main mit aufgenommen werden? @noopliez

**Comment by noopliez** [comment]
Wenn die Warnungen weg sind, kann das hier auf `done` bzw. erstell doch mal nen PR und verlink die Issue hier.
