### ISSUE TITLE
Endpoint View bei Medizin fehlt

### ISSUE THREAD

**Issue by noopliez** [Schlaue-Lise-IT-Project/schlaue-lise#55]
![Screen Shot 2021-11-26 at 13 41 44](https://user-images.githubusercontent.com/71688793/143582861-89b44b6c-6aee-4e01-bc32-7d27c9dfa315.png)

Wie im Screeenshot zu sehen, fehlt die Ausgabe der Einrichtungen, in denen man Hilfe findet. 

Die Info

> ... gehe zu 'Medizin-Übersicht'

ist m.M.n. auch veraltet.

**Comment by Pusteblum3** [comment]
![image](https://user-images.githubusercontent.com/56924575/143610623-e0318e8b-34c9-4b12-b6ba-c9ae04f55d0b.png)

In den uns zur Verfügung gestellten XD-Projekt waren nur 3 Screens für Medizin enthalten. Hier gab es nur eine Auflistung der Adressen für "nicht krankenversicherte" (siehe Screenshot rechts). Wenn man "nicht versichert" angibt, sollte die eine Adresse die angegeben ist auch ausgegeben werden. 

Da es für "versichert" keine Adresse aus dem XD-Projekt gab, habe ich die Ausgabe erst einmal so gelassen. 
Erachtest du es für sinnvoll, hier dann einfach auch eine "ergoogelte" Adresse hinzuzufügen in der Ausgabe für den Versicherungsstatus "versichert" bzgl. Vollständigkeit? @noopliez

**Comment by Pusteblum3** [comment]
Info "... gehe zu 'Medizin-Übersicht'" wurde entfernt aus stories und rules

**Comment by noopliez** [comment]
Ok das wusste ich nicht, dass es da keine Auflistung gibt. Für _nicht versichert_ gibt es allerdings 2 Adressen. 

- [ ] Kannst du die fehlende noch aktualisieren? 

<img width="412" alt="Screen Shot 2021-11-29 at 05 23 55" src="https://user-images.githubusercontent.com/71688793/143808683-103e98a5-ee54-429b-9551-9a2632ab2b49.png">
