### ISSUE TITLE
Rasa X Erklärung

### ISSUE THREAD

**Issue by MarieConstantin** [Schlaue-Lise-IT-Project/schlaue-lise#78]
Bitte noch eine kurze Erklärung was Rasa X ist und wie es funktioniert mit in die Readme schreiben.

Bitte vom Branch "marie/readme" einen neuen Branch ziehen und darauf arbeiten und dann einen merge-Request dafür erstellen mit mir (Marie) als Reviewer.
Danke

**Comment by noopliez** [comment]
Habe leider gepushed, [hier](https://github.com/Schlaue-Lise-IT-Project/schlaue-lise/commit/43e7700de7d07a9c87cf4c32ac5ae0569738b0d1) sind die Änderungen zu sehen.
