### ISSUE TITLE
Pipeline Deployment ins Readme aufnehmen

### ISSUE THREAD

**Issue by MarieConstantin** [Schlaue-Lise-IT-Project/schlaue-lise#80]
Bitte noch den Absatz für das Pipeline Deployment im Readme ergänzen.

Dazu bitte einen Branch vom Branch "marie/readme" erstellen und darauf arbeiten. Wenn fertig einen Merge-Request dafür erstellen, mit mir (Marie) als Reviewer.
Danke

**Comment by noopliez** [comment]
Habe leider gepushed, [hier](https://github.com/Schlaue-Lise-IT-Project/schlaue-lise/commit/43e7700de7d07a9c87cf4c32ac5ae0569738b0d1) sind die Änderungen zu sehen.
