### ISSUE TITLE
Überarbeiten der README & des User Manuals

### ISSUE THREAD

**Issue by noopliez** [Schlaue-Lise-IT-Project/schlaue-lise#9]
Das [README](https://github.com/Schlaue-Lise-IT-Project/schlaue-lise/blob/main/README.md) und das [User Manual](https://github.com/Schlaue-Lise-IT-Project/schlaue-lise/blob/main/user-manual.md) müssen überarbeitet bzw. ausgefüllt werden. 

Folgende Dinge gilt es dabei zu beachten:

- Das ganze ist unser _Bericht_, achtet also darauf, dass dort sinnvolle Sachen stehen
- Es ist auf gendergerechte Sprache zu achten; wir verwenden den Binnendoppelpunkt (bspw. Anwender:innen)
- Nutzt Absätze in langen Texten, das wird sonst zu anstrengend zu lesen
- Nutzt die Backticks (\`\`), wenn ihr etwas hervorheben wollt, was mit dem Code zu tun hat oder anstelle von Anführungszeichen (bspw. `conda`)

Aktuelle Tasks (bitte erweitern)

- [x] User Manual (Schlafen)
- [x] User Manual (Hygiene)
- [x] User Manual (Spenden)
- [x] User Manual (Medizin)
- [x] README

**Comment by MarieConstantin** [comment]
@Pusteblum3 @noopliez @Sebastian-Klement @Lena-Holderrieth bitte oben abhaken, wenn ihr eure Sachen im User Manual fertig habt, damit ich mich dann an die Vereinheitlichung und Benutzerfreundlichkeit machen kann. Danke!

**Comment by Lena-Holderrieth** [comment]
@MarieConstantin soll ich noch was zur URL in das User Manual schreiben?

**Comment by Pusteblum3** [comment]
@MarieConstantin habe im user-manual noch ein zwei kleine Änderungen bzgl. Gendern gemacht. Sollte jetzt so passen. Habe es nun oben abgehakt

**Comment by noopliez** [comment]
@Sebastian-Klement machst du das für Schlafen & Hygiene? Bzw ist das nicht schon fertig?

**Comment by Sebastian-Klement** [comment]
In der readme hab ich ja nichts zu tun. Im usermanual hab ich soweit auch alles gemacht. Von meiner Seite sollte alles passen.

**Comment by MarieConstantin** [comment]
> @MarieConstantin soll ich noch was zur URL in das User Manual schreiben?

Das wäre glaub ich ganz gut. Eine kleine Erklärung was es ist und wie es funktioniert.
